- user:
    login: neil
    password: verizon
    level: admin

- user:
    login: tony
    password: extreme
    level: admin

- user:
    login: jim
    password: extreme
    level: user

- snmp:
    snmpReadOnly: g
    snmpReadWrite: h
    snmpWriteView: '"i"'
    emptyVariable: ""
    anotherEmpty: ""
